### PR TITLE
Introduce configurable navigation styles

### LINKED ISSUE #549: Navigation Drawer - Configurable Styles
### Description

Discussed Here: https://discourse.nodered.org/t/override-or-customise-baseline-layout/85160

Options should include:

- Default - As is, hamburger to open/close
- Fixed Open - Always on display, cannot be closed
- Icon Only when Closed - When "closed", we still display just the icon for each navigation option
- Hidden - No side navigation at all

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

Introduces configurable navigation to Dashboard at a dashboard wide level.

### Settings Screen

Screenshot 2024-02-14 at 14 41 40
Screenshot 2024-02-14 at 14 41 44

#### Default
Screenshot 2024-02-14 at 14 28 34

#### None
Screenshot 2024-02-14 at 14 28 18

#### Appear Over
Screenshot 2024-02-14 at 14 28 04

#### Fixed
Screenshot 2024-02-14 at 14 27 48

#### Icons
Screenshot 2024-02-14 at 14 27 34

## Related Issue(s)

Fixes #549

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
The alignment in the "Icons" view looks a little off, can we make the icon view wide so it aligns with the hamburger menu in the top-left?

**Comment by joepavitt** [comment]
Okay, so this works in desktop view, but when below `1280px` width, Vuetify seems to takeover with an alternative layout which needs to be investigated.

**Comment by joepavitt** [comment]
Just checking status as time conscious for tomorrow @Pezmc - expectations on where it will be?

**Comment by Pezmc** [comment]
> The alignment in the "Icons" view looks a little off, can we make the icon view wide so it aligns with the hamburger menu in the top-left?

We can adjust the width of the column, but Vuetify doesn't center the icons, so it looks a little off:

Screenshot 2024-02-14 at 18 18 40

**Comment by Pezmc** [comment]
> Okay, so this works in desktop view, but when below 1280px width, Vuetify seems to takeover with an alternative layout which needs to be investigated.

@joepavitt Seems to apply to the fixed and default layouts only, we can configure the [mobile-breakpoint](https://vuetifyjs.com/en/api/v-navigation-drawer/#props-mobile-breakpoint) as we'd like (or turn it off), but not sure we want to disable that feature as it makes it pretty unusable on mobile

**Comment by joepavitt** [comment]
> Seems to apply to the fixed and default layouts only, we can configure the [mobile-breakpoint](https://vuetifyjs.com/en/api/v-navigation-drawer/#props-mobile-breakpoint) as we'd like (or turn it off), but not sure we want to disable that feature as it makes it pretty unusable on mobile

Tricky - for a starting point, I'm tempted to change mobile breakpoint to be more mobile than 1280, maybe the classic 768? Then force it into overlay mode, _unless_ the user has defined _Always Hide_, in which case, we obey that?

**Comment by joepavitt** [comment]
> We can adjust the width of the column, but Vuetify doesn't center the icons, so it looks a little off:

I'm happy to override some CSS here

**Comment by Pezmc** [comment]
Handled in [91b018d](https://github.com/FlowFuse/node-red-dashboard/pull/579/commits/91b018d5afbe808ebea5f50ce19651c6485acd4f) and [9fc8371](https://github.com/FlowFuse/node-red-dashboard/pull/579/commits/9fc837131461d4f37159482507d707119fab4d92), I'll leave the CSS hacking to you!

**Comment by joepavitt** [comment]
Suits me - thanks @Pezmc - I'll handle this tomorrow.

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
