### PR TITLE
Third Party Widget Support

### LINKED ISSUE #174: Support external/third-party widgets
### Description

Dashboard 1.0 supported the ability to utilise third-party UI nodes, e.g. https://flows.nodered.org/node/node-red-node-ui-table

Currently our architecture requires code to leave within our own repo, it only considers widgets found in `/ui`, and not any third-party contributions.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by joepavitt**
### Features
- Add support for `config.onInput`, `config.methods` and `config.onMounted` functions on client-side `ui-template`. This means that it's easy to extend the Vue component generated for the custom widgets (and could also be utilised for https://github.com/flowforge/flowforge-nr-dashboard/issues/115)
- Modify behaviour in`App.vue` when finding the relevant Vue component so that it falls back to `ui-template` if the `props.type` is not explicitly found in Dashboard core.
- Adds `onSocket` to the `evts` when registering a Widget so that you can handle custom SocketIO events that are transmitted by Vue widgets using `vue.$socktet.emit()`

### Documentation
- Adds a lot of documentation on how to build your own third party widgets
- Details the `.register()` function available on `ui-base`, `ui-page` and `ui-group` as that's very important for widget registration and integration. 

## Related Issue(s)

Closes #174 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [x] Documentation has been updated

### CODE REVIEW

**Comment by joepavitt** [comment]
As a first pass I am happy with the progress here and think this is ready for a first push, features supported:

- [x] Write HTML in a third party widget and have that render in Dashboard 2.0 UI
- [x] Call `send()` or `submit()` from that third party HTML
- [x] Define VueJS functions in a third party widget and have that functional client-side:
    - [x] onInput
    - [x] onMounted
    - [x] General Methods
- [x] Define JS in a third party widget and have that functional client-side, e.g. raw JS or jQuery (all within VueJS functions)
- [x] Ability to emit (via socketio) custom events from client and handle them accordingly on the server-side
- [x] Ability to define JS dependencies/third-party libraries for the client

**Comment by bartbutenaers** [comment]
Hi @joepavitt,
Looks very good!  
Do you know when this feature will become available?  
I assume this will be part of version ***0.5.0***, or am I mistaken?
Thanks!!

**Comment by joepavitt** [comment]
I got it working as of late Friday, and didn't want to do a cut without proper checks in place.

Will be Tuesday morning (I don't work Mondays)

**Comment by joepavitt** [comment]
It'll go in as a new 0.6.0

**Comment by bartbutenaers** [comment]
Ok thanks for the info!
Please don't hurry with this!!
I was just wondering in which version ot would end up...

**Pull request merged**
