### PR TITLE
dependency: Update vitepress to stable version

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
@joepavitt Correct, and now the blog is built on v1.0.2 instead of rc40

**Comment by joepavitt** [comment]
v1.0.2 of what though? Lots of updates in lock

**Comment by ZJvandeWeg** [comment]
I ran `npm update vitepress` -- Assumed it would bump all requirements for just vitepress.

**Comment by joepavitt** [comment]
okay, it hasn't changed the `package.json` at all though, which still lists the `rc.40`

**Comment by ZJvandeWeg** [comment]
@joepavitt Updated the PR

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
