### PR TITLE
UI Gauge - Add Tank Style

### LINKED ISSUE #1192: Gauge Type: Tank Level
Potentially two types here:

- Tank Style
- Circular (which was very popular in Dashboard 1.0

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- Adds "Water Tank" Gauge type
- Configurable as per other gauges
- Shows water/wave animation
- Add documentation

### Known Issues

- Resizing window causes a break in the SVG clip pathing, which I'm okay with shipping _for now_, and will do a follow up issue/resolution

### Demo

https://github.com/user-attachments/assets/b4670ddf-19c7-4626-b171-ba35aba0fd7d

### Todo

- Add E2E to ensure it renders properly

## Related Issue(s)

Closes #1192

### CODE REVIEW

**Review by gayanSandamal — COMMENTED** [review]
Water levels are not visible when set the size as a square (3x3, 4x4, etc...) because it detects the orientation as horizontal.

@joepavitt  is this the expected behaviour?

Screenshot 2024-08-12 at 11 17 01

Screenshot 2024-08-12 at 11 16 32

Tested on Chrome, EDGE, Firefox and Safari. Everything works fine other than above reported behaviour

**Comment by Steve-Mcl** [comment]
I too see tank level not shown in certain sizes. (`wl1 2x2`, `wl2 6x1`, `wl3 3x2`)
NOTE: The battery gauge  at 6x1 is also not showing level

Additionally, the black text is not visible when I chose a dark colour (`wl5`)

Lastly, in smaller height gauges `wl2 6x1` (battery too `b2 6x1`), the thickness of the outer is somewhat overpowering. 

chrome_ze2hPXIt4W


```
[{"id":"a774e60fc7557ac3","type":"inject","z":"f80624abfd69b02e","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"1","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"(\t    $minimum := 1;\t    $maximum := 10;\t    $round(($random() * ($maximum-$minimum)) + $minimum, 0)\t)","payloadType":"jsonata","x":1290,"y":160,"wires":[["31ecdd62ca8e9de5","f9d9c480108b9fd1"]]},{"id":"4f5fa3becff2aa28","type":"inject","z":"f80624abfd69b02e","name":"","props":[{"p":"ui_control.label","v":"fault","vt":"str"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"fault","x":1300,"y":200,"wires":[["f9d9c480108b9fd1"]]},{"id":"1ce7443d3fd4fd67","type":"inject","z":"f80624abfd69b02e","name":"","props":[{"p":"ui_control.label","v":"normal","vt":"str"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"normal","x":1300,"y":240,"wires":[["f9d9c480108b9fd1"]]},{"id":"60ec1ead3443dc96","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":1,"width":"2","height":"2","gtype":"gauge-battery","gstyle":"needle","title":"b1 2x2","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#ea5353"},{"from":"4","color":"#ffc800"},{"from":"7","color":"#5cd65c"}],"min":0,"max":"10","sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1640,"y":160,"wires":[]},{"id":"13ae613ccd37b183","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":2,"width":"2","height":"2","gtype":"gauge-water-tank","gstyle":"needle","title":"wl1 2x2","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#5cd65c"},{"from":"4","color":"#ffc800"},{"from":"7","color":"#ea5353"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1830,"y":160,"wires":[]},{"id":"5bbfaa0c7db976d7","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":3,"width":"6","height":"1","gtype":"gauge-battery","gstyle":"needle","title":"b2 6x1","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#ea5353"},{"from":"4","color":"#ffc800"},{"from":"7","color":"#5cd65c"}],"min":0,"max":"10","sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1640,"y":200,"wires":[]},{"id":"172d5c5cda3f795b","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":4,"width":"6","height":"1","gtype":"gauge-water-tank","gstyle":"needle","title":"wl2 6x1","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#5cd65c"},{"from":"4","color":"#ffc800"},{"from":"7","color":"#ea5353"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1830,"y":200,"wires":[]},{"id":"ee833568fa02539e","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":5,"width":"1","height":"5","gtype":"gauge-battery","gstyle":"needle","title":"b3 1x5","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#ea5353"},{"from":"1","color":"#ffc800"},{"from":"2","color":"#5cd65c"}],"min":0,"max":"3","sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1640,"y":240,"wires":[]},{"id":"f662109bd214223b","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":6,"width":"1","height":"5","gtype":"gauge-water-tank","gstyle":"needle","title":"wl3 1x5","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#5cd65c"},{"from":"1","color":"#ffc800"},{"from":"2","color":"#ea5353"}],"min":0,"max":"3","sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1830,"y":240,"wires":[]},{"id":"9b16accabd941cbf","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":7,"width":"3","height":"2","gtype":"gauge-battery","gstyle":"needle","title":"b4 3x2","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#f89696"},{"from":"1","color":"#333333"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1640,"y":280,"wires":[]},{"id":"57e49dbb906d28ab","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":8,"width":"3","height":"2","gtype":"gauge-water-tank","gstyle":"needle","title":"wl4 3x2","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#5cd65c"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1830,"y":280,"wires":[]},{"id":"7e3c4c44d22d6c97","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":9,"width":"2","height":"3","gtype":"gauge-battery","gstyle":"needle","title":"b5 2x3","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#373434"},{"from":"10","color":"#5cd65c"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1640,"y":320,"wires":[]},{"id":"105f2eb5cf0bbef8","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":10,"width":"2","height":"3","gtype":"gauge-water-tank","gstyle":"needle","title":"wl5 2x3","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#050505"},{"from":"10","color":"#11ee2a"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1830,"y":320,"wires":[]},{"id":"627ee70aa40f9d2e","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":11,"width":"1","height":"3","gtype":"gauge-battery","gstyle":"needle","title":"b6 1x3","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"10","color":"#5cd65c"},{"from":"0","color":"#ea5353"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1640,"y":360,"wires":[]},{"id":"d57a2f1e425a40a1","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":13,"width":"1","height":"3","gtype":"gauge-water-tank","gstyle":"needle","title":"wl6 1x3","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"7","color":"#ea5353"},{"from":"4","color":"#ffc800"},{"from":"0","color":"#5cd65c"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1830,"y":360,"wires":[]},{"id":"72038b62470fe699","type":"inject","z":"f80624abfd69b02e","name":"0","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"0","payloadType":"num","x":1520,"y":460,"wires":[["151e14bd6bd71851","08b568ebeef5ed09"]]},{"id":"1cec13c1121203bc","type":"inject","z":"f80624abfd69b02e","name":"10","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"10","payloadType":"num","x":1520,"y":520,"wires":[["fb375419af970c02","a401314974a404c5"]]},{"id":"08b568ebeef5ed09","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":19,"width":"1","height":"2","gtype":"gauge-water-tank","gstyle":"needle","title":"wl-mt 1x2","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#5cd65c"},{"from":"4","color":"#ffc800"},{"from":"7","color":"#ea5353"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1850,"y":460,"wires":[]},{"id":"151e14bd6bd71851","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":18,"width":"1","height":"2","gtype":"gauge-battery","gstyle":"needle","title":"b-mt 1x2","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#ea5353"},{"from":"4","color":"#ffc800"},{"from":"7","color":"#5cd65c"}],"min":0,"max":"10","sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1670,"y":460,"wires":[]},{"id":"fb375419af970c02","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":20,"width":"1","height":"2","gtype":"gauge-battery","gstyle":"needle","title":"b-full 1x2","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#ea5353"},{"from":"4","color":"#ffc800"},{"from":"7","color":"#5cd65c"}],"min":0,"max":"10","sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1670,"y":520,"wires":[]},{"id":"a401314974a404c5","type":"ui-gauge","z":"f80624abfd69b02e","name":"","group":"5c9407416fba1d1b","order":21,"width":"1","height":"2","gtype":"gauge-water-tank","gstyle":"needle","title":"wl-full 1x2","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#5cd65c"},{"from":"4","color":"#ffc800"},{"from":"7","color":"#ea5353"}],"min":0,"max":10,"sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1850,"y":520,"wires":[]},{"id":"31ecdd62ca8e9de5","type":"junction","z":"f80624abfd69b02e","x":1410,"y":160,"wires":[["79afada40d824509"]]},{"id":"f9d9c480108b9fd1","type":"junction","z":"f80624abfd69b02e","x":1410,"y":240,"wires":[["2dd53643df28b205"]]},{"id":"2dd53643df28b205","type":"junction","z":"f80624abfd69b02e","x":1490,"y":240,"wires":[["60ec1ead3443dc96","5bbfaa0c7db976d7","ee833568fa02539e","9b16accabd941cbf","7e3c4c44d22d6c97","627ee70aa40f9d2e"]]},{"id":"79afada40d824509","type":"junction","z":"f80624abfd69b02e","x":1730,"y":240,"wires":[["13ae613ccd37b183","172d5c5cda3f795b","f662109bd214223b","57e49dbb906d28ab","105f2eb5cf0bbef8","d57a2f1e425a40a1"]]},{"id":"5c9407416fba1d1b","type":"ui-group","name":"PR-1123","page":"868aaffa6da2e1ce","width":"6","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"868aaffa6da2e1ce","type":"ui-page","name":"PR-1123","ui":"22ea43815413e748","path":"/page13","icon":"home","layout":"grid","theme":"c2ff5ba1f92a0f0e","order":1,"className":"","visible":"true","disabled":"false"},{"id":"22ea43815413e748","type":"ui-base","name":"base","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false,"navigationStyle":"default","titleBarStyle":"default"},{"id":"c2ff5ba1f92a0f0e","type":"ui-theme","name":"Default","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]
```

#### personal observation. 
When water tank is full, the wave is still visible - would making the base of the water level the value then clip top of the wave as being out of bounds make it a little more realistic? (so at 100% it looks like the full battery gauge does, at 97% it has a clipped wave etc, but the base of the wave aligns with the battery)

chrome_QonpI2iBPP

**Comment by Steve-Mcl** [comment]
Few more observations / suggestions (feel free to ignore):

1. Would this be better named simply as "tank" since it could be oil, coolant, grain, plastic pellets? Or is the intention to add other tank types?
2. When switching between tank and battery, my settings are reset :( 
   1. I carefully enter 10 different colours + values 
   2. I realise I selected "tank" instead of "battery"
   3. I select "battery" - all my colour table entries are reverted.
3. Levels and colours flip from value to value very "immediately" unlike the needle gauge colours and needle position which have beautiful transitions.
    chrome_fZ8qhZLSpv

**Comment by SynoUser-NL** [comment]
@joepavitt : very cool addition.
Thanks!

**Comment by joepavitt** [comment]
> Would this be better named simply as "tank" since it could be oil, coolant, grain, plastic pellets? Or is the intention to add other tank types?

Very Sensible

> When switching between tank and battery, my settings are reset :

This was intentional. The default segments are only really applicable to the "Standard" gauges, and I want to present alternative defaults for tank/battery. as such, when you switch type, they set the new defaults.

Otherwise, users have to manually setup sensible tank or battery colours manually, and that's going to be more annoying.

> Levels and colours flip from value to value very "immediately" unlike the needle gauge colours and needle position which have beautiful transitions.

We could, yes, although I'd say not necessary as an MVP worthy and blocking the PR

**Comment by joepavitt** [comment]
The other frustration I have is the masking - as you've demonstrated, a black fill means that the text is unreadable. I could re-implement the masking, but it makes the text very difficult to read when the liquid cuts it.

The other alternative I have is to give the text a black outline, but that then breaks the "flat" aesthetic of the Dashboard

**Comment by joepavitt** [comment]
> would making the base of the water level the value then clip top of the wave as being out of bounds make it a little more realistic? (so at 100% it looks like the full battery gauge does, at 97% it has a clipped wave etc, but the base of the wave aligns with the battery)

Possibly, but then at 0, you'd still see the wave. No exaggeration that I spent about 12 hours, working until 00:30 on Saturday night and again from 05:45 on the Sunday morning in order to get this as clean as it is 😮‍💨

**Comment by joepavitt** [comment]
> Water levels are not visible when set the size as a square (3x3, 4x4, etc...) because it detects the orientation as horizontal.

Fixed

**Comment by joepavitt** [comment]
> NOTE: The battery gauge at 6x1 is also not showing level

Less concerned with this atm as the solution is just "make it taller", and not relevant to this, _Tank_ PR.

**Comment by joepavitt** [comment]
> Additionally, the black text is not visible when I chose a dark colour (wl5)

This one, for now, the advice will just be, don't use black as a colour. To get that SVG mask working with the waves was a _PAIN_. When I finally did get it working, it makes the text very difficult to read.

**Comment by joepavitt** [comment]
> Levels and colours flip from value to value very "immediately" unlike the needle gauge colours and needle position which have beautiful transitions.

We're using the `div` as a height tracker, animating that causes problems as when it then goes to set the height of the SVG `mask`, it reads partway into the animation, and therefore sets the clipping path wrong.

There are ways around it, but for the sake of another day's work, i don't think it's worth it at this stage

**Comment by Steve-Mcl** [comment]
Is this ready for re-review @joepavitt?

when we spoke, you were like 85% sure you were gonna change the text to permit visibility on dark filled tanks (but i dont see a commit for this)

**Comment by joepavitt** [comment]
I've not had a chance to implement that with all the out-of-work stuff going on my side at the moment

**Comment by joepavitt** [comment]
@Steve-Mcl pushed this, isn't not too clean imo, but it's the best we can do atm

Screenshot 2024-08-16 at 20 43 02
Screenshot 2024-08-16 at 20 43 19
Screenshot 2024-08-16 at 20 43 11

**Review by Steve-Mcl — APPROVED** [review]
good with me @joepavitt

**Pull request merged**
