### PR TITLE
WYSIWYG: Widget resizing and re-ordering

### LINKED ISSUE #1468: WYSIWYG Widget sizing and re-ordering wihin a group

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #1468

## Description

* Adds widget reordering (within its own group)
* Adds widget resizing
* Adjusts CSS of sizing handles to make them less opaque/less obtrusive when not editing a widget
  * they are raised to opacity 1 upon hover/active
* Re-worked the deploy to node-red promise chain to async await (was able to crash Node-RED)

### screenshots

chrome_CnOvBpBlUv

## Related Issue(s)

 #1468

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Playing around with this locally and it's just _excellent_. I've modified a little CSS here and there for the hover and make it clearer where the widgets start/finish, even when not hovered.

**Comment by joepavitt** [comment]
6 x Slider E2E failures, which is very odd and potentially overlaps with the issues we've seen in the Slider tests with https://github.com/FlowFuse/node-red-dashboard/pull/1488 too

**Comment by Steve-Mcl** [comment]
> 6 x Slider E2E failures, which is very odd and potentially overlaps with the issues we've seen in the Slider tests with #1488 too

Yes, as https://github.com/FlowFuse/node-red-dashboard/pull/1488 is based off this branch (since it affects an area re-written in this PR and I didnt want to fix the HTTP issue twice)

The problem most likely lives in this branch.

Invistigating.

**Comment by Steve-Mcl** [comment]
@joepavitt - tests passing now (except 1 random ui-control test)

```
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  widgets/control.spec.js                  00:25       11        9        2        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤

    ✖  1 of 27 failed (4%)                      04:11      131      129        2        -        -  
```

**Comment by joepavitt** [comment]
Tests running fine locally, functionality also working well locally.

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
