### PR TITLE
UI Gauge - Add in "tile" gauge type

### LINKED ISSUE #737: Gauge Type: Tile
### Description

image (5)

In manufacturing, most OEM-built HMI's look like the above. Currently, in Dashboard 2.0 this is not trivial to build because it would require `ui-template`, or custom CSS in a `ui-text`.

Configuration-wise, it would have a lot of overlap with `ui-gauge`, including labelling, value thresholds associated with colours, etc.

Having a "tile" gauge type would make building such Dashboards considerably easier.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by joepavitt**
## Description
Screenshot 2024-04-03 at 17 38 09

- Add new "tile" type for `ui-gauge` which is a solid block colour (defined by the segments) and renders the label centrally as per common Manufacturing HMIs
- Break `UIGauge` into multiple sub widgets for easier control over functionality
- Add documentation (in-Editor and online)
- Add E2E tests to ensure correct type is rendered

## Related Issue(s)

Closes #737 

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
@hotnipi - FYI as I'd mentioned a little while ago, I've now broken the `UIGauge` down to sub-types, so logic can live separately, and it makes it easier to add more variations.

**Review by Steve-Mcl — APPROVED** [review]
Approved as is, but with a new issue to raise around un-ordered segments not matching up.  

chrome_2iR2S8MHPK


And while this is closely related to #558, it is more likely in tile mode, a single value will represent the colour meaning any future additions made by users would require manual re-ordering for it to work.

**Comment by Steve-Mcl** [comment]
@joepavitt here is the flow JSON for the above GIF

```
[{"id":"44f6d648a4eff20b","type":"inject","z":"4dc48d85b98236c1","name":"set fault","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"2","payloadType":"num","x":1150,"y":980,"wires":[["6731fdaa5ba2bad4"]]},{"id":"6827479dd675b308","type":"inject","z":"4dc48d85b98236c1","name":"clear fault","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"1","payloadType":"num","x":1140,"y":1020,"wires":[["6731fdaa5ba2bad4"]]},{"id":"124d30018103aaae","type":"ui-gauge","z":"4dc48d85b98236c1","name":"","group":"925ed89cd235b6ab","order":7,"width":3,"height":3,"gtype":"gauge-tile","gstyle":"needle","title":"NORMAL","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"0","color":"#d9d9d9"},{"from":"1","color":"#3dff64"},{"from":"2","color":"#fb3737"}],"min":0,"max":"2","sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1460,"y":1020,"wires":[]},{"id":"ab939fd5df6201b3","type":"ui-gauge","z":"4dc48d85b98236c1","name":"","group":"925ed89cd235b6ab","order":7,"width":3,"height":3,"gtype":"gauge-tile","gstyle":"needle","title":"NORMAL","units":"units","icon":"","prefix":"","suffix":"","segments":[{"from":"1","color":"#5cd65c"},{"from":"2","color":"#ff3d3d"},{"from":"0","color":"#e6e6e6"}],"min":0,"max":"2","sizeThickness":16,"sizeGap":4,"sizeKeyThickness":8,"styleRounded":true,"styleGlow":false,"className":"","x":1460,"y":980,"wires":[]},{"id":"7eb0a1eedfa4581f","type":"inject","z":"4dc48d85b98236c1","name":"default state","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"0","payloadType":"num","x":1170,"y":940,"wires":[["6731fdaa5ba2bad4"]]},{"id":"6731fdaa5ba2bad4","type":"junction","z":"4dc48d85b98236c1","x":1300,"y":980,"wires":[["ab939fd5df6201b3","124d30018103aaae"]]},{"id":"925ed89cd235b6ab","type":"ui-group","name":"English","page":"9081e3b45e851c75","width":"6","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"9081e3b45e851c75","type":"ui-page","name":"Page 1","ui":"22ea43815413e748","path":"/page1","icon":"home","layout":"grid","theme":"c2ff5ba1f92a0f0e","order":-1,"className":"","visible":"true","disabled":"false"},{"id":"22ea43815413e748","type":"ui-base","name":"base","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false},{"id":"c2ff5ba1f92a0f0e","type":"ui-theme","name":"Default","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]
```

**Comment by joepavitt** [comment]
Have fixed the breakage when they're not ordered correctly @Steve-Mcl - thanks for pointing it out.

**Pull request merged**
