### PR TITLE
SocketIO - Override default SocketIO reconnection

### LINKED ISSUE #620: Widget state not updated after network disconnection and recovery
If the network connection with the browser fails, and then a widget state (eg ui-text node) is updated by sending it a message, then when the network recovers the new state is not reflected in the browser.

To replicate, import the flow below, or recreate it.  
Run a browser showing the editor on the machine running node red and run a browser on another machine showing the dashboard.
Check that clicking the inject nodes updates the text in the browser showing the dashboard.
Disconnect the network from the machine showing the dashboard and wait for the connection error messages to appear in the developer console.
On the machine showing the editor click the other inject node.
Reconnect the network to the machine running the browser.  The text shown in the dashboard does not update to show the new value.  Refreshing the browser page does update it correctly.

With D1, running the equivalent test, the text does update to the new value automatically on network recovery.

Edit: I am still seeing this with dashboard version 1.8.0

image

```
[{"id":"7235e7106295e0eb","type":"ui-text","z":"318b3c8445d47122","group":"d8734fb40940c231","order":0,"width":0,"height":0,"name":"ui-text test","label":"The label","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":460,"y":740,"wires":[]},{"id":"153ccf4715b87682","type":"inject","z":"318b3c8445d47122","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Text One","payloadType":"str","x":220,"y":720,"wires":[["7235e7106295e0eb"]]},{"id":"302c888d24db31a3","type":"inject","z":"318b3c8445d47122","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Text Two","payloadType":"str","x":220,"y":780,"wires":[["7235e7106295e0eb"]]},{"id":"d8734fb40940c231","type":"ui-group","name":"Charger","page":"f33c25a3d1e68ab9","width":"6","height":"1","order":-1,"showTitle":false,"className":""},{"id":"f33c25a3d1e68ab9","type":"ui-page","name":"Charger","ui":"04ee189a49c54f22","path":"/charger","layout":"flex","theme":"23aa79f4e489b044","order":8,"className":""},{"id":"04ee189a49c54f22","type":"ui-base","name":"Dashboard","path":"/dashboard"},{"id":"23aa79f4e489b044","type":"ui-theme","name":"Theme 1","colors":{"surface":"#ffffff","primary":"#514fba","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"},"sizes":{"pagePadding":"1px","groupGap":"1px","groupBorderRadius":"4px","widgetGap":"10px"}}]
```

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

Details on the fix found [here](https://github.com/FlowFuse/node-red-dashboard/issues/620#issuecomment-2079425251)

This video shows my Android phone running the Dashboard, within which:

1. Send a timestamp to show the connection is live
2. Disable the WiFi and get warned that the SocketIO is disconnected
3. Try to send a new message to the Dashboard and show the phone doesn't receive it
4. I turn on my phone's WiFi, and see the phone has reconnected
5. Send a "String" to the `ui-text` node and show that it updates on the phone.

https://github.com/FlowFuse/node-red-dashboard/assets/99246719/27ca5197-a2bb-4fc3-a766-22572496114e

## Related Issue(s)

Fixes #620

### CODE REVIEW

**Comment by joepavitt** [comment]
This _might_ also cover https://github.com/FlowFuse/node-red-dashboard/issues/444

**Comment by colinl** [comment]
> This _might_ also cover #444

I think there is a good chance it will. Are you going for a release so I can test it over the weekend?

**Comment by joepavitt** [comment]
> Are you going for a release so I can test it over the weekend?

Subject to @cstns fitting in some late Friday reviewing - yes 😄

**Review by cstns — APPROVED** [review]
LGTM, Happy testing!

**Comment by colinl** [comment]
Looking good so far on the re connection recovery (though not on templates, as you suggested), but I have just seen something that I saw once on the previous release, I think.  There is a browser error
```
index-DkPQtye5.js:52 
 Uncaught TypeError: Cannot read properties of null (reading 'close')
    at Array.<anonymous> (index-DkPQtye5.js:52:17055)
    at Object.emit (index-DkPQtye5.js:52:12243)
    at Socket.<anonymous> (index-DkPQtye5.js:244:408641)
    at Emitter.emit (index-DkPQtye5.js:236:20532)
    at Socket.onclose (index-DkPQtye5.js:236:49311)
    at Emitter.emit (index-DkPQtye5.js:236:20532)
    at Manager.onclose (index-DkPQtye5.js:236:56619)
    at Emitter.emit (index-DkPQtye5.js:236:20532)
    at lt.onClose (index-DkPQtye5.js:236:39496)
    at addEventListener.hostname.offlineEventListener (index-DkPQtye5.js:236:33850)
```
but I am not sure exactly when it occurred.  After that the `disconnected' popup does not appear when the network is disconnected. A refresh recovers the situation. I will see if I can make it happen again.

**Pull request merged**
