### PR TITLE
UI Gauge - Improve text size across different gauge sizes

### LINKED ISSUE #888: UI Gauge - Improve icon sizing at varying sizes
### Current Behavior

https://discourse.nodered.org/t/gauge-icon-text-sizing/88176

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

- Dashboard version:
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- By no means a "perfect" solution, but it's better than we have.
- This is a complicated problem given the variations available for gauge sizing and types of gauges available.

## Related Issue(s)

Closes #888 

Some impact on #769 too

## Examples

https://github.com/FlowFuse/node-red-dashboard/assets/99246719/0201b3f4-4aad-4347-b0ef-ce090f21f506

### CODE REVIEW

**Review by cstns — COMMENTED** [review]
This appears to be a D3 implementation detail rather than a dashboard-specific one. 

While having an out-of-the-box solution is beneficial and simplifies usage, users should be aware of this and have the ability to override line heights and font sizes or disable the feature altogether. 

Otherwise, it might complicate matters for those that want to add custom styling.

**Comment by joepavitt** [comment]
You're right to a certain extent, but the sizings are driven by `css` classes:

```
/* Size Overrides */

/* xs */
.nrdb-ui-gauge-size-xs .nrdb-ui-gauge-value span {
    font-size: 1.5rem;
    line-height: 1.75rem;
}

/* sm */
.nrdb-ui-gauge-size-sm .nrdb-ui-gauge-value span {
    font-size: 2rem;
    line-height: 2.25rem;
}

/* md */
.nrdb-ui-gauge-size-md .nrdb-ui-gauge-value span {
    font-size: 2.5rem;
    line-height: 3rem;
}
.nrdb-ui-gauge-size-md .nrdb-ui-gauge-value label {
    font-size: 1rem;
    line-height: 1.25rem;
}

/* lg */
.nrdb-ui-gauge-size-lg .nrdb-ui-gauge-value span {
    font-size: 3rem;
    line-height: 3.25rem;
}
```

So can be overriden within a user's own CSS too

**Comment by cstns** [comment]
Yes, that should be mentioned in the docs somewhere so users won't have to dig through the code base to find that out.

Other than that I don't any see technical improvement that could be made. I found a scaling solution which uses the d3 lib to place a watcher on the window and updates graph .tick (labels) font-size on window resize:
```js
d3.select(window).on("resize", function() {
    const newWidth = d3.select("svg").style("width");
    const newFontSize = 10 * (600 / parseInt(newWidth));
    d3.selectAll(".tick").select("text")
        .style("font-size", newFontSize)
});
```
I don't think it brings much to the table except for not using breakpoints to scale font-size and has the drawback of not being overwritten.

I feel that the approach you took is better for this use case

**Comment by joepavitt** [comment]
Thanks Serban - would appreciate a review along with the comments :)

**Comment by joepavitt** [comment]
Docs for class overrides added @cstns

**Review by cstns — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
