### PR TITLE
UI Base - Add option to control title bar behaviour/styling

### LINKED ISSUE #645: Option to hide the title bar
### Description

In the regular dashboard for Node-Red, it's possible to hide the title bar which is useful to save some vertical space if left menu is always shown. This is a feature I am currently missing and would love to see added. It is found under `Dashboard -> Site -> Options -> Hide the title bar`.

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- Adds three options for how to render the title bar: "Default", "Hidden" and "Fixed"
- Adds docs
- Falls back to "default" for backwards compatability

## Related Issue(s)

Closes #645

### CODE REVIEW

**Comment by joepavitt** [comment]
### Demo:

https://github.com/FlowFuse/node-red-dashboard/assets/99246719/3c029c51-52ff-4127-8baf-2376610928a8

**Comment by joepavitt** [comment]
Failing test is the standard WS inconsistency

**Review by cstns — COMMENTED** [review]
Looks good!

**Review by cstns — APPROVED** [review]

**Comment by nileio** [comment]
awesome - looking forward to try this feature

**Pull request merged**
