### PR TITLE
Slider text field

### LINKED ISSUE #1063: UI Slider - Text Field Input
### Description

https://discourse.nodered.org/t/numeral-entry-in-dashboard-2-slider/89256

Available as a property in Vuetify's slider widget: https://vuetifyjs.com/en/components/sliders/#append-text-field

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by cgjgh**
## Description

Adds an optional text field for number input next to slider.

https://github.com/user-attachments/assets/ba271903-2645-4501-bfb1-ca904e58589c

## Related Issue(s)

Closes #1063
## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [x] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Seeing 2 x E2E failures in the `slider.spec.js` that'll need reviewing please @cgjgh - otherwise, this is an excellent addition

**Comment by cgjgh** [comment]
@joepavitt Yes, I'm aware of it, I added two tests for input max/min validation, they work using `cypress open` but fail with `cypress run` - seems text field blur is not firing consistently... any ideas?

**Comment by joepavitt** [comment]
Thanks as always @cgjgh - another great addition, although, whilst it does bind well with the slider when changing from the slider side, two issues spotted when changing the value directly in the text input:

- It doesn't emit an event back into Node-RED when only changing the text field
- If you have steps in place, e.g. 0-10 with steps of 2, and you put in a number that isn't valid because the steps, but is valid because of the range - the slider will update correctly, but the text-field doesn't correct itself

I think you may need to bind the `text-field` to a different model value, then handle the events accordingly.

**Review by joepavitt — CHANGES_REQUESTED** [review]
Thanks as always @cgjgh - another great addition, although, whilst it does bind well with the slider when changing from the slider side, two issues spotted when changing the value directly in the text input:

- It doesn't emit an event back into Node-RED when only changing the text field
- If you have steps in place, e.g. 0-10 with steps of 2, and you put in a number that isn't valid because the steps, but is valid because of the range - the slider will update correctly, but the text-field doesn't correct itself

I think you may need to bind the text-field to a different model value, then handle the events accordingly.

**Comment by cgjgh** [comment]
@joepavitt I believe this is ready for review now. I hope my contributions, despite my limited experience, are more help than hassle.

**Review by joepavitt — APPROVED** [review]

**Comment by joepavitt** [comment]
Looks great - just waiting for one final E2E test pass

**Pull request merged**
