### PR TITLE
Switch button group label as text

### PR DESCRIPTION
**Pull request by m-schaeffler**
## Description

The CSS classes of the labels of `ui-switch` and `ui-buttongroup` are changed according to `ui-text`:
- in the template `v-label` is replaced by a name according to the general naming style
- the style definition is amended so that it is similar to `ui-text`

## Related Issue(s)

This gives a consistent UI experience.

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

### CODE REVIEW

**Comment by joepavitt** [comment]
Agree with the move, although, rather than having disparate classes defined in each widget, we could have a higher level `nrdb-ui-label` class in `/stylesshets/common.css` and then use that class in the relevant `ui-text`, `ui-switch` and `ui-button-group` locations?

**Review by joepavitt — COMMENTED** [review]
Agree with the move, although, rather than having disparate classes defined in each widget, we could have a higher level nrdb-ui-label class in /stylesshets/common.css and then use that class in the relevant ui-text, ui-switch and ui-button-group locations?

**Comment by m-schaeffler** [comment]
@joepavitt Yes, I think your Idea is the better solution

**Comment by m-schaeffler** [comment]
please do it in one gig shot.
Remark: this hard coded color is already in several components.

**Pull request closed without merging**
