### PR TITLE
Customizable PWA icon support

### PR DESCRIPTION
**Pull request by gayanSandamal**
## Description

Screenshot 2024-10-07 at 16 51 15

Screenshot 2024-10-07 at 16 58 23

## Related Issue(s)

https://github.com/FlowFuse/node-red-dashboard/issues/1328

### Notes
- Icons doesn't need to come from the FlowFuse assets as this supports icons from any origin 
- Docs and built-in help are updated in a previous PR https://github.com/FlowFuse/node-red-dashboard/pull/1334
- Need to restart the node-red server to apply the new icon

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Screenshot 2024-10-07 at 15 50 45

This branch doesn't seem to contain the code in order to configure the icon?

**Comment by gayanSandamal** [comment]
> Screenshot 2024-10-07 at 15 50 45
> This branch doesn't seem to contain the code in order to configure the icon?

This is my bad. I forgot to get changes from the main branch (#1144-configurable-pwa-icon) related with this issue. Just updated

**Review by Steve-Mcl — APPROVED** [review]
Looks good to me.

Question, shouldnt the name come from the base node?

image

As it stands, all of my dashboards are called "Node-RED Dashboard 2.0" - not a great UX IMHO.

This can of course be a follow up task.

**Comment by gayanSandamal** [comment]
> Looks good to me.
> 
> Question, shouldnt the `name` come from the base node `Name` field?
> 
> image
> 
> As it stands, all of my dashboards are called "Node-RED Dashboard 2.0" - not a great UX IMHO.
> 
> This can of course be a follow up task.

@Steve-Mcl As discussed a followup task has been raised https://github.com/FlowFuse/node-red-dashboard/issues/1375

**Pull request merged**
