### PR TITLE
Moved "Motivation" section right above "License" section

### PR DESCRIPTION
**Pull request by gayanSandamal**
## Description

Moved "Motivation" section right above "License" section.

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Review by joepavitt — APPROVED** [review]
Thanks Gayan - Would also be good to add a section above `Installation` that shows off some example dashbaords/visualisations.

**Comment by gayanSandamal** [comment]
> Thanks Gayan - Would also be good to add a section above `Installation` that shows off some example dashbaords/visualisations.

That would be a good idea. How about a section called "Live Demo" with some screenshots of the interactive documentation and a link to the interactive dashboard charts?

**Comment by joepavitt** [comment]
A link to interactive dashboard for sure, I think we could make a single Dashboard that was a bit cleaner in it's layout though and showed more diverse widgets on a single Dashboard.

**Comment by gayanSandamal** [comment]
> A link to interactive dashboard for sure, I think we could make a single Dashboard that was a bit cleaner in it's layout though and showed more diverse widgets on a single Dashboard.

In that case, I will create a new page with more diverse widgets in the demo instance and move it as the first page.

**Pull request merged**
