### PR TITLE
App icon detailed documentation

### PR DESCRIPTION
**Pull request by gayanSandamal**
## Description

Screenshot 2024-10-11 at 14 58 08

@joepavitt let me if you think the screenshots are too much

Screenshot 2024-10-11 at 14 59 01

## Related Issue(s)

#1144 (Configurable PWA Icon)

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [x] Documentation has been updated
    - [ ] Upgrade instructions
    - [x] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
They're okay, but maybe make them smaller and centrally align them to the page

**Comment by joepavitt** [comment]
You've also mentioned it requires a URL, does this not work with a local file URI?

**Comment by gayanSandamal** [comment]
> They're okay, but maybe make them smaller and centrally align them to the page

Sure, I will update

> You've also mentioned it requires a URL, does this not work with a local file URI?

This doesn't require an external URL, we can also add the image to FFC assets and refer from there

**Comment by gayanSandamal** [comment]
@joepavitt I've updated image sizes and alignments

Screenshot 2024-10-11 at 17 38 01

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
