### PR TITLE
Form dropdown support

### PR DESCRIPTION
**Pull request by bartbutenaers**
## Description

This PR allows support for form elements of type *'dropdown'*:

image

I introduced tabsheets, to be able to add a second editableList for the dropdown options:

image

In the first column you can select all available form elements of type 'dropdown'.
Note: when a form element of type 'dropdown' is removed (or when its key is changed in the first tabsheet) then the corresponding dropdown options will become detached:

image

Then the user can decide what to do with the detached options: delete them or attach them to another dropdown (e.g. when the dropdown key has been changed).

In the dashboard, the dropdown looks like this:

image

The dropdown options (currently of all dropdowns at once) can be updated dynamically via `msg.ui_update`, as in the following example flow:
```
[{"id":"1140f1281d2121ad","type":"ui-form","z":"4aad778b57d4f47b","name":"","group":"c2bf863890b3eab0","label":"","order":0,"width":0,"height":0,"options":[{"label":"List A","key":"list_A","type":"dropdown","required":true,"rows":null}],"formValue":{"list_A":""},"payload":"","submit":"submit","cancel":"clear","resetOnSubmit":true,"topic":"topic","topicType":"msg","splitLayout":"","className":"","passthru":false,"dropdownOptions":[{"dropdown":"","key":"a","label":"Static a"},{"dropdown":"","key":"b","label":"Static b"}],"x":1230,"y":400,"wires":[[]]},{"id":"63ce850b80ebafb8","type":"inject","z":"4aad778b57d4f47b","name":"Dropdown options","props":[{"p":"ui_update","v":"{\"dropdownOptions\":[{\"dropdown\":\"list_A\",\"key\":\"x\",\"label\":\"Dynamic x\"},{\"dropdown\":\"list_A\",\"key\":\"y\",\"label\":\"Dynamic y\"}]}","vt":"json"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1050,"y":400,"wires":[["1140f1281d2121ad"]]},{"id":"c2bf863890b3eab0","type":"ui-group","name":"Scenario's","page":"e06eacf47a88bb87","width":"6","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"e06eacf47a88bb87","type":"ui-page","name":"Alarm","ui":"be29745a6e568f30","path":"/page9","icon":"lock","layout":"grid","theme":"a965ccfef139317a","order":2,"className":"","visible":true,"disabled":false},{"id":"be29745a6e568f30","type":"ui-base","name":"UI Name","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control","ui-chart","ui-text-input","ui-dropdown"],"showPathInSidebar":false,"titleBarStyle":"default"},{"id":"a965ccfef139317a","type":"ui-theme","name":"Default","colors":{"surface":"#404040","primary":"#109fbc","bgPage":"#e8e8e8","groupBg":"#d6d6d6","groupOutline":"#6fbc10"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]
```

Known issues:
+ Both editableLists don't fill the entire available height.  Could have added some CSS, but you guys will have better ways to do that ;-)

Hopefully you guys like it...

## Related Issue(s)

Issue [814](https://github.com/FlowFuse/node-red-dashboard/issues/814)

## Checklist

 - [X] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by bartbutenaers** [comment]
This PR is ready for review.  Thanks!

**Comment by joepavitt** [comment]
Finally got round to testing this - it's UX isn't perfect by any means, by it's an _excellent_ improvement on what we have.

**Comment by joepavitt** [comment]
Am making a few changes:

- "Outlined" style for the dropdown to ensure it fits in style with the rest of the form
- Changing `key` > `value` and `Name` to `Label` to better reflect what they're used for in the dropdown itself.

**Comment by joepavitt** [comment]
I think this is all good to go now :+1:

**Pull request merged**
