### PR TITLE
Refactor adding of ui nodes  to ensure valid configuration

### LINKED ISSUE #1401: Drag in first node creates phantom "unused config nodes" issue
### Current Behavior

Starting from nothing - drag button into, it is preconfigured.

image

It creates 4 config nodes

image

Everything seems really ok
But if you deploy

image
image

It renders on dashboard but unused configs still exist on every deploy.
And there's no clue what the user should do with them.

Refresh the browser tab clears the issue. 

No difference if you have fresh install of the dashboard or if you just clear everything dashboard related to start over.

### Expected Behavior

Adding first node to flow should be seamless. 

### Steps To Reproduce

_No response_

### Environment

- Dashboard version: 1.18.0
- Node-RED version: 4.0.2
- Node.js version: 20.14.0
- npm version:
- Platform/OS: Windows 10 
- Browser: Chrome latest

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #1401

## Description

Refactor adding of ui nodes  to ensure valid configuration.

This was achieved by encapsulating the logic of adding and assigning of "things" into helper functions that "do the right thing"

This fixes:
* Default adding of base/theme/1st group when a node is dragged onto empty workspace
  * Applies default base AND updates the bases `user` array
* Adding Links
  * Applies default base
  * Ensures base nodes `users` are updated
* Adding Pages
  * Applies default base and theme
  * Ensures base nodes `users` are updated
* Adding Groups via the "Add Group" button
* Ensures the pages `users` array is updated
* Applies unique names to pages to avoid the dreaded "same page path" issue
* Adds links to the end (like pages are)
* Increments Page and Link names while ensuring they dont clash with existing page/link names

### Before (Existing behaviour in V1.18.1)

Demonstrates:
* links added with name "Link" everytime - making it difficult to decern
* links added without a base set
* links added to top of list instead of bottom
* page name/path clashes when next page already exists
* new page base not set
* new theme base not set

chrome_9ECyrsMGVL

### After

Reduced friction when adding links and pages

chrome_s45I7tXbiw

No "unused configs" toast in node-red when adding 1st node

chrome_S3sa37659K

## Related Issue(s)

#1401

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
This is all great @Steve-Mcl - am still seeing an Unused Config Node message for "UI Link" nodes though? I think it's because it's being used by only other config nodes? It's never linked back to the "normal" nodes?

**Comment by Steve-Mcl** [comment]
> This is all great @Steve-Mcl - am still seeing an Unused Config Node message for "UI Link" nodes though? I think it's because it's being used by only other config nodes? It's never linked back to the "normal" nodes?

Bah!

Could you tell me the steps to make this happen please - i will fix it.

**Comment by joepavitt** [comment]
> Could you tell me the steps to make this happen please - i will fix it.

Click "+ Link" in the sidebar, and any link added gets 0 "users"

**Comment by Steve-Mcl** [comment]
> > > Could you tell me the steps to make this happen please - i will fix it.
> > 
> > 
> > Click "+ Link" in the sidebar, and any link added gets 0 "users"
> 
> Ah man, must have been a last minute refactor! ok, thanks Joe. will get this sorted.

Sorted

chrome_JJiF3q7EkY

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
