### PR TITLE
Buttongroup json format

### LINKED ISSUE #776: ButonGroup: add JSON aus output format
### Description

Please add JSON as a possible output format for button group.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

### PR DESCRIPTION
**Pull request by bartbutenaers**
## Description

Currently the buttongroup node only allows the following value types: string, number and boolean.
This pull request allows also ***json*** as extra value type.

It was easier as I expected, because everything seems to work correctly without any extra code changes (in both directions):

buttongroup_json_demo

```
[{"id":"7732b63a899a1a82","type":"ui-button-group","z":"f624e6564f974a57","name":"Json button group","group":"f90f857366c11ce8","order":1,"width":"3","height":1,"label":"button group","rounded":true,"useThemeColors":true,"passthru":false,"options":[{"label":"Option1","icon":"","value":"{\"myprop\":true}","valueType":"json","color":"#009933"},{"label":"Option2","icon":"","value":"{\"myprop\":false}","valueType":"json","color":"#999999"}],"topic":"topic","topicType":"msg","x":850,"y":620,"wires":[["416a44d2ee247638"]]},{"id":"416a44d2ee247638","type":"debug","z":"f624e6564f974a57","name":"Selection","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1040,"y":620,"wires":[]},{"id":"a9925dc3a5c0f2f0","type":"inject","z":"f624e6564f974a57","name":"{\"myprop\":true}","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"myprop\":true}","payloadType":"json","x":640,"y":620,"wires":[["7732b63a899a1a82"]]},{"id":"3215978924f561e6","type":"inject","z":"f624e6564f974a57","name":"{\"myprop\":false}","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"myprop\":false}","payloadType":"json","x":640,"y":660,"wires":[["7732b63a899a1a82"]]},{"id":"f90f857366c11ce8","type":"ui-group","name":"Demo","page":"8604ea49340f9d41","width":"3","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"8604ea49340f9d41","type":"ui-page","name":"Home","ui":"be29745a6e568f30","path":"/page1","icon":"home","layout":"grid","theme":"092547d34959327c","order":-1,"className":"","visible":"true","disabled":"false"},{"id":"be29745a6e568f30","type":"ui-base","name":"UI Name","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false},{"id":"092547d34959327c","type":"ui-theme","name":"Theme Name","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"}}]
```

## Related Issue(s)

Closes #776 

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by bartbutenaers** [comment]
Could it be that there is a (general) issue with the automated tests?  Because it seems weird to me that adding "json" would cause this kind of test failures...

**Review by joepavitt — CHANGES_REQUESTED** [review]
The selection and emission works fine, but the when injected selection is done, the custom colours don't seem to be assigned for JSON values - it works fine when clicked though.

This line comparator is where it falls down:

https://github.com/bartbutenaers/node-red-dashboard/blob/31c31e419be52857f94ea423645f91c31e54903a/ui/src/widgets/ui-button-group/UIButtonGroup.vue#L82

**Comment by bartbutenaers** [comment]
@joepavitt
Thanks for the thorough testing!

It seems that checking the equality of two objects in javascript isn't that easy.  Didn't see that one coming...
Not sure what would be the best way to implement it:

1. Comparison via `===` or `==` does not work, because it compares if both variables refer to the same value.
2. It looks like Vue does the comparison correctly, but I cannot find at first sight whether it is possible to ask Vue to compare two objects.
3. Comparsion via `JSON.stringify(a) === JSON.stringify(b)` is not really good, because it requires that the order of the keys is the same in both objects.  And some other issues.
4. The best solution for deep comparison (of nested objects) seems to be the `isEqual` function from [Lodash](https://github.com/lodash/lodash).  But loading an entire library for 1 function looks like killing a mosquito with a huge cannon.
5. I was wondering if it would be perhaps useful to load the [lodash.isequal](https://www.npmjs.com/package/lodash.isequal) package via Vite into the bundle?  The package seems to be very old, but based on the number of downloads I assume it is rather good...
6. Writing a custom isEqual functions seems like reinventing hot water, if you have option 5 available.

Any thoughts?

**Comment by bartbutenaers** [comment]
> The package seems to be very old

Don't think that old lodash.isEqual version is a problem.  When you look at the Lodash [commit history](https://github.com/lodash/lodash/commits/main/src/.internal/equalObjects.ts) of the equalObjects.ts (and its predecessor equalObjects.js), you will see that in more recent versions there was only less important changes like e.g. linting.

So personally I would go for option 5...

**Comment by joepavitt** [comment]
We currently use 3. inside `UISwitch.vue`, for a first iteration, I'd have no concern with that

**Comment by colinl** [comment]
How does the core Filter node do the comparison?

**Comment by bartbutenaers** [comment]
@joepavitt
Option 3 solves the problem with the custom colors:

demo_custom_colors
```
[{"id":"a72c14cf179fc335","type":"ui-button-group","z":"f624e6564f974a57","name":"Json button group","group":"f90f857366c11ce8","order":1,"width":"3","height":1,"label":"button group","rounded":true,"useThemeColors":false,"passthru":false,"options":[{"label":"Option1","icon":"","value":"{\"myprop\":true}","valueType":"json","color":"#990026"},{"label":"Option2","icon":"","value":"{\"myprop\":false}","valueType":"json","color":"#3ba702"}],"topic":"topic","topicType":"msg","x":1510,"y":80,"wires":[["0b9a5d089002fa33"]]},{"id":"0b9a5d089002fa33","type":"debug","z":"f624e6564f974a57","name":"Selection","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1700,"y":80,"wires":[]},{"id":"1a162101a862e9fc","type":"inject","z":"f624e6564f974a57","name":"{\"myprop\":true}","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"myprop\":true}","payloadType":"json","x":1300,"y":80,"wires":[["a72c14cf179fc335"]]},{"id":"cf6f6ad619411421","type":"inject","z":"f624e6564f974a57","name":"{\"myprop\":false}","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"myprop\":false}","payloadType":"json","x":1300,"y":120,"wires":[["a72c14cf179fc335"]]},{"id":"f90f857366c11ce8","type":"ui-group","name":"Demo","page":"8604ea49340f9d41","width":"3","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"8604ea49340f9d41","type":"ui-page","name":"Home","ui":"be29745a6e568f30","path":"/page1","icon":"home","layout":"grid","theme":"092547d34959327c","order":-1,"className":"","visible":"true","disabled":"false"},{"id":"be29745a6e568f30","type":"ui-base","name":"UI Name","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false},{"id":"092547d34959327c","type":"ui-theme","name":"Theme Name","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"}}]
```

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
